### ISSUE TITLE
Argument "-TERM" isn't numeric in kill

### ISSUE THREAD

**Issue by rkleemann** [Test-More/Test2-Harness#125]
Trying to `cpanm install Test2::Harness` on Perls 5.12-5.16 (works on 5.18 forward), and I consistently get a hang of a half hour before failing the install.  The last lines of the build.log are consistent:

> ...
> ( PASSED )  job 30    t/Test2/Harness/Job/Dir.t
> ( SKIPPED)  job 31    t/Test2/Harness/Job/Runner.t  -  TODO
> ( SKIPPED)  job 32    t/Test2/Harness/Job/Runner/Dummy.t  -  TODO
> ( SKIPPED)  job 33    t/Test2/Harness/Job/Runner/Fork.t  -  TODO
> ( SKIPPED)  job 34    t/Test2/Harness/Job/Runner/IPC.t  -  TODO
> ( SKIPPED)  job 35    t/Test2/Harness/Job/Runner/Open3.t  -  TODO
> ( SKIPPED)  job 36    t/Test2/Harness/Logger.t  -  TODO
> ( SKIPPED)  job 37    t/Test2/Harness/Logger/JSONL.t  -  TODO
> ( SKIPPED)  job 38    t/Test2/Harness/Preload.t  -  TODO
> ( SKIPPED)  job 39    t/Test2/Harness/Renderer.t  -  TODO
> ( SKIPPED)  job 40    t/Test2/Harness/Renderer/Formatter.t  -  TODO
> ( SKIPPED)  job 41    t/Test2/Harness/Renderer/JSONL.t  -  TODO
> ( SKIPPED)  job 42    t/Test2/Harness/Run.t  -  TODO
> ( SKIPPED)  job 43    t/Test2/Harness/Run/Dir.t  -  TODO
> ( SKIPPED)  job 44    t/Test2/Harness/Run/Queue.t  -  TODO
> ( SKIPPED)  job 45    t/Test2/Harness/Run/Runner.t  -  Not done, come back!
> ( SKIPPED)  job 46    t/Test2/Harness/Run/Runner/Persist.t  -  TODO
> ( STDERR )  job 47    Argument "-TERM" isn't numeric in kill at /Users/bkleemann/.cpanm/work/1579712488.18077/Test2-Harness-0.001099/lib/Test2/Harness/Run/Runner/ProcMan.pm line 136.
> ( STDERR )  job 47    Argument "-TERM" isn't numeric in kill at /Users/bkleemann/.cpanm/work/1579712488.18077/Test2-Harness-0.001099/lib/Test2/Harness/Run/Runner/ProcMan.pm line 136.
> ( STDERR )  job 47    Argument "-TERM" isn't numeric in kill at /Users/bkleemann/.cpanm/work/1579712488.18077/Test2-Harness-0.001099/lib/Test2/Harness/Run/Runner/ProcMan.pm line 136.

**Comment by exodist** [comment]
What platform are you on? Linux, windows, mac, other?

**Comment by exodist** [comment]
Also, can you pull down the 'major_refactor' branch from git and see if it gives you the same issue?

**Comment by rkleemann** [comment]
It's on a Mac.  I'll pull down the branch and let you know...

**Comment by rkleemann** [comment]
Pulled down the 'major_refactor' branch, ran `perl Makefile.PL && make && make test` and got the following output:

> ...
> "/Users/bkleemann/.plenv/versions/5.12.5/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/yath
> Manifying 1 pod document
> Manifying 81 pod documents
> PERL_DL_NONLAZY=1 "/Users/bkleemann/.plenv/versions/5.12.5/bin/perl" "-Iblib/lib" "-Iblib/arch" test.pl
> 1..1
> Undefined subroutine &App::Yath::Script::run called at /Users/bkleemann/Work/other/Test2-Harness/scripts/yath line 222.
> Undefined subroutine &App::Yath::Script::run called at /Users/bkleemann/Work/other/Test2-Harness/scripts/yath line 222.
> not ok 1 - Passed tests when run by yath (allow fork)
> yath exited with 65280not ok 2 - Passed tests when run by yath (no fork)
> yath exited with 65280make: *** [test_dynamic] Error 255

**Comment by exodist** [comment]
Hmm, I wonder if there is a platform specific issue. So far Test2::Harness has only been developed/tested on linux AFAIK. I would like support on other platforms, but I do not have any other platforms here to test against. I do think your first issue is solved in the branch, your second issue is confusing to me, not sure why/how that can happen.

**Comment by rkleemann** [comment]
The original issue is clearly an issue with using symbolic signal names, rather than the numeric equivalents.  There is a solution for 5.12 mentioned in "Signals" in `perlipc` for using names portably: https://perldoc.perl.org/5.12.5/perlipc.html#Signals (scroll down till you see `use Config;`)

As for the second issue listed, where there's an undefined subroutine, I have no idea what's causing that.  I'll dig into it, and get back to you with any discoveries.

**Comment by exodist** [comment]
The sub should be generated a few linea above the error in a call to App::Yath->generate_run_sub

**Comment by rkleemann** [comment]
After installing/upgrading numerous modules, running `make test` with the major_refactor branch on the system Perl (5.18.2) for Mac produces a small set of errors.  Would you like those errors listed here, or in separate issue?

After installing/upgrading numerous modules, running `make test` with the major_refactor branch on Perl 5.12.5, I still get the same issue (Undefined subroutine).  I'm still digging into that one.

**Comment by exodist** [comment]
You can list the errors here.

**Comment by rkleemann** [comment]
The aforementioned errors on 5.18.2 on my Mac:

```
Subroutine Test2::Harness::Runner::signal redefined at /Users/bkleemann/Work/other/Test2-Harness/blib/lib/Test2/Harness/Runner.pm line 171.

# Failed test 'lib/Test2/Tools/HarnessTester.pm POD has correct package 'Test2::Tools::HarnessTester' under NAME'
# at t/1-pod_name.t line 44.
# +---------------------------------+----+---------------------------------+
# | GOT                             | OP | CHECK                           |
# +---------------------------------+----+---------------------------------+
# | Test2::Harness::HarnessTester - | =~ | (?^:^Test2\:\:Tools\:\:HarnessT |
# |  Tools for t                    |    | ester\ \-\ .+$)                 |
# +---------------------------------+----+---------------------------------+
# All files with errors:
# lib/Test2/Tools/HarnessTester.pm
# Seeded srand with seed '20200123' from local date.
    # Failed test 'Found file in expected spot'
    # at t/unit/App/Yath/Util.t line 128.
    # +-------------------------------+----+-------------------------------+
    # | GOT                           | OP | CHECK                         |
    # +-------------------------------+----+-------------------------------+
    # | /private/var/folders/vn/jy1qm | eq | /var/folders/vn/jy1qm87s217_t |
    # | 87s217_t14nx37qptzc0000gn/T/t |    | 14nx37qptzc0000gn/T/tJ_EPk5fY |
    # | J_EPk5fYx/nest/nest_a/thefile |    | x/nest/nest_a/thefile         |
    # +-------------------------------+----+-------------------------------+
    # Failed test 'Found file in expected spot'
    # at t/unit/App/Yath/Util.t line 131.
    # +-------------------------------+----+-------------------------------+
    # | GOT                           | OP | CHECK                         |
    # +-------------------------------+----+-------------------------------+
    # | /private/var/folders/vn/jy1qm | eq | /var/folders/vn/jy1qm87s217_t |
    # | 87s217_t14nx37qptzc0000gn/T/t |    | 14nx37qptzc0000gn/T/tJ_EPk5fY |
    # | J_EPk5fYx/thefile             |    | x/thefile                     |
    # +-------------------------------+----+-------------------------------+

# Failed test 'find_in_updir'
# at t/unit/App/Yath/Util.t line 132.
    # Failed test 'Found it in a config path'
    # at t/unit/App/Yath/Util.t line 62.
    # +-------------------------------+----+-------------------------------+
    # | GOT                           | OP | CHECK                         |
    # +-------------------------------+----+-------------------------------+
    # | /var/folders/vn/jy1qm87s217_t | eq | /private/var/folders/vn/jy1qm |
    # | 14nx37qptzc0000gn/T/erPyZBysg |    | 87s217_t14nx37qptzc0000gn/T/e |
    # | n/scripts/yath                |    | rPyZBysgn/scripts/yath        |
    # +-------------------------------+----+-------------------------------+

# Failed test 'find_yath'
# at t/unit/App/Yath/Util.t line 63.
# Seeded srand with seed '20200123' from local date.
    # Failed test 'File must be executable'
    # at t/unit/Test2/Harness/TestFile.t line 474.
    # +-------------------------------+----+-------------------------------+
    # | GOT                           | OP | CHECK                         |
    # +-------------------------------+----+-------------------------------+
    # | Cannot run binary test file ' | eq | Cannot run binary test file ' |
    # | /private/var/folders/vn/jy1qm |    | /var/folders/vn/jy1qm87s217_t |
    # | 87s217_t14nx37qptzc0000gn/T/y |    | 14nx37qptzc0000gn/T/yDb3NctJ_ |
    # | Db3NctJ_E/binary': file is no |    | E/binary': file is not execut |
    # | t executable.\n               |    | able.\n                       |
    # +-------------------------------+----+-------------------------------+

# Failed test 'binary'
# at t/unit/Test2/Harness/TestFile.t line 512.
# Caught exception in subtest: (Die On Fail) at t/unit/Test2/Harness/TestFile.t line 474.
(Die On Fail) at t/unit/Test2/Harness/TestFile.t line 512.
# Seeded srand with seed '20200123' from local date.
# Tests were run but no plan was declared and done_testing() was not seen.
(Die On Fail) at /Library/Perl/5.18/Test/Builder.pm line 147.
END failed--call queue aborted at t/unit/Test2/Harness/TestFile.t line 68.
Failed 3/102 test programs. 4/727 subtests failed.
make: *** [test_dynamic] Error 255
```

**Comment by rkleemann** [comment]
Playing with the code in various ways between tasks at work today, I can see that something goes awry around `$options->process_option_post_actions($cmd);` in `generate_run_sub` in lib/App/Yath.pm, as `warn` statements before that line are seen, but not after that.

Running `perl Makefile.PL && make && make test` works on 5.18.2, but not on 5.12.5, but if I `perl Makefile.PL && make` on 5.18.2, and the `make test` on 5.12.5, it "works" (in the sense it gets past that initial issue), but it's got *lots* of errors.  Reversing it, and doing `perl Makefile.PL && make` on 5.12.5 and then running `make test` on 5.18.2 causes the same error (Undefined subroutine).

A wild stab in the dark would be a missing dependency in the build steps for 5.12.5?

**Comment by exodist** [comment]
Have you tried 5.14? I went to try it in 5.12 and got stopped since dzil will not install that far back

**Comment by exodist** [comment]
Ah, using a dist built by dzil I was able to then try to install it on 5.12 and duplicated your error.

**Comment by rkleemann** [comment]
No luck with 5.12.5, nor 5.14.4.  5.16.3 seems to work (with the aforementioned errors for 5.18.2).

**Comment by exodist** [comment]
Looks like the 5.12 problem is with the lvalue usage in `$settings->yath->persist_file = $val`  This first triggers in PreCommand options post_process, but any lvalue usage seems to cause the issue. The issue seems to break out of the BEGIN block in the yath script without generating any kind of error message.

**Comment by exodist** [comment]
aha, got an error message:
`
217     my $ok = eval { $app->generate_run_sub('App::Yath::Script::run'); 1 };
218     my $err = $@;
219     print "XXX: $ok - $err\n";
`
Resulted in:
`
XXX:  - Can't return a temporary from lvalue subroutine at /home/exodist/projects/Test2/Test2-Harness/Test2-Harness-1.000000/lib/App/Yath/Options/PreCommand.pm line 124.`

**Comment by exodist** [comment]
The lvalue is defined in App::Yath::Settings::Prefix lines 23->33, but is sometimes triggered via autoload on lines 36->48

**Comment by exodist** [comment]
Hmm, the issue may be lvalue limitations in perls older than 5.16

I am trying to decide if it is worth it to remove the lvalue usage all over the place (including external uses at $work) or if I just need to set the minimum version to 5.16. I can probably leave the lvaue for external things, but not use it internally... have to think about it.

**Comment by exodist** [comment]
The 'util.t' test failures you listed are path errors, and I will try to fix them in a bit. I am not sure what the problem is with the binary test in TestFiles, I will have to take a deeper look at that.

**Comment by rkleemann** [comment]
It would be nice for Test2 to be usable on older Perls, so distributions that want to support older Perls can do so with the same test suite.  With that said, given how old 5.14 is, it's understandable if it's not entirely supported.
 
As far as the various test files, yes, some of the issues appear easy to fix (paths), and some will require a bit more digging.  I'll look forward to hearing you've solved those problems.

**Comment by exodist** [comment]
I believe the test failures related to paths have been fixed now, please give them a try.

**Comment by rkleemann** [comment]
On the system Perl for Mac, I got one warnings, and two errors:

```
t/0-load_all.t ................................. 1/? Subroutine Test2::Harness::Runner::signal redefined at /Users/bkleemann/Work/other/Test2-Harness/blib/lib/Test2/Harness/Runner.pm line 171.
...
t/unit/App/Yath/Util.t ......................... 1/?     # Failed test 'Found it in a config path'
    # at t/unit/App/Yath/Util.t line 62.
    # +-------------------------------+----+-------------------------------+
    # | GOT                           | OP | CHECK                         |
    # +-------------------------------+----+-------------------------------+
    # | /var/folders/vn/jy1qm87s217_t | =~ | (?^:\/private\/var\/folders\/ |
    # | 14nx37qptzc0000gn/T/CIUk1mwPY |    | vn\/jy1qm87s217_t14nx37qptzc0 |
    # | z/scripts/yath                |    | 000gn\/T\/CIUk1mwPYz\/scripts |
    # |                               |    | \/yath$)                      |
    # +-------------------------------+----+-------------------------------+

# Failed test 'find_yath'
# at t/unit/App/Yath/Util.t line 63.
# Seeded srand with seed '20200124' from local date.
```

**Comment by exodist** [comment]
can you explain to my what /private is, and why mac (or just your mac?) is adding it to path names? Where is it coming from? From what I am seeing it looks like /private is just a link to /? or a dir that has /* folders linked inside it? I am very confused.

**Comment by rkleemann** [comment]
I'm not an expert on Macs, and why they have the file layout that they do, but `/private` is consistent across all of the Macs I've used for many more years than I can remember.  `/etc`, `/tmp`, and `/var` are all symlinked into `/private/{etc,tmp,var}`.

**Comment by rkleemann** [comment]
In a quick test on the master branch, I changed all occurrences of `kill` from their symbolic values (`HUP`, `INT`, and `TERM`) into their numeric equivalents (`1`, `2`, and `15`) and ran `make test` on 5.12.5, and got one test error:

```
...
( PASSED )  job 17    t/App/Yath/Plugin/Git.t
( STDERR )  job 18    %Config::Config is read-only
( FAILED )  job 18    t/App/Yath/Plugin/SysInfo.t
< REASON >  job 18    Test script returned error (Err: 255)
< REASON >  job 18    ----- START -----
No plan was declared, and no assertions were made.
< REASON >  job 18    ------ END ------
( PASSED )  job 19    t/App/Yath/Util.t
...
```

**Comment by rkleemann** [comment]
Updating the `major_refactor` branch this morning, and running `perl Makefile.PL && make && make test`, I see that it still fails on 5.12 and 5.14 with the `Unknown subroutine` error, but 5.16 fails for another reason in the `Passed tests when run by yath (no fork)` portion:

```
(INTERNAL)     ----- START -----
Argument "-TERM" isn't numeric in kill at /Users/bkleemann/Work/other/Test2-Harness/lib/Test2/Harness/Runner.pm line 150, <$fh> line 131.
(INTERNAL)     ------ END ------
( TIMEOUT)  job  1    ----- START -----
Test2::Harness checks for timeouts at a configurable interval, if a test does
not produce any output to stdout or stderr between intervals it will be
forcefully killed under the assumption it has hung. See the '--event-timeout'
option to configure the interval.
( TIMEOUT)  job  1    ------ END ------
< TIMEOUT>  job  1    ----- START -----
A timeout (event) has occured, job was forcefully killed
< TIMEOUT>  job  1    ------ END ------
( FAILED )  job  1    t/integration/failure_cases.t
< REASON >  job  1    Errors were encountered (Count: 1)
```

And it has one warning from a job a little later on:

```
( STDERR )  job  9    ----- START -----
cannot remove path when cwd is /private/var/folders/vn/jy1qm87s217_t14nx37qptzc0000gn/T/yath-Test2-Harness-45389-Ihi3ammH/076F6846-46BC-11EA-9CB0-CE9474CAE528/077D83C2-46BC-11EA-9CB0-CE9474CAE528+0/tmp/mVz1iXZBQH for /private/var/folders/vn/jy1qm87s217_t14nx37qptzc0000gn/T/yath-Test2-Harness-45389-Ihi3ammH/076F6846-46BC-11EA-9CB0-CE9474CAE528/077D83C2-46BC-11EA-9CB0-CE9474CAE528+0/tmp/mVz1iXZBQH:  at /Users/bkleemann/.plenv/versions/5.16.3/lib/perl5/5.16.3/File/Temp.pm line 902.
( STDERR )  job  9    ------ END ------
( PASSED )  job  9    t/integration/init.t
```

5.18 passes completely, without warnings.

**Comment by exodist** [comment]
Ok, I think I have fixes for most of the issues in this ticket. See my latest push to major_refactor. The kill issue only occurred with negative signal names, and I have worked around that in the one place they are used. I have made it so that the lvalue stuff is not used internally, though is still supported by third party plugins and such. I have verified that all tests pass back to 5.10 on linux at least.

**Comment by rkleemann** [comment]
After running `for v in $( plenv versions --bare ) system ; do make realclean && plenv shell $v && echo $v && perl Makefile.PL && make && make test || break ; done ; unset v`

I can confirm that the major_refactor branch appears to pass all tests on all versions from 5.12.5 through 5.30.0, and the system Perl (5.18.2).

Thank you!
